### ISSUE TITLE
Touchscreen issue persists

### ISSUE THREAD

**Issue by Bauuuuu** [armani-dev/android_kernel_xiaomi_armani#17]
https://github.com/armani-dev/android_kernel_xiaomi_armani/commit/7687212b3b2c083ac1929d3957239c76098bd886

I guess its wise to lower the config_hz to original 100 value. There are still plenty of phones for whom the touchscreen does not work, most likely those repaired touchscreens are not compatible with 200 hz even...

**Comment by fefifofum** [comment]
Mmmkay...

**Comment by fefifofum** [comment]
I'll make a test build and ask some of those users to confirm if this works:

https://review.cyanogenmod.org/#/c/174024/

**Comment by Bauuuuu** [comment]
http://forum.xda-developers.com/redmi-1s/help/touch-screen-t3492940/post69842269#post69842269 
somewhere here to test
